apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: AbishekSMahesh-poi-map-app-dev
  annotations:
    argocd/app-name: AbishekSMahesh-poi-map-app-dev
    backstage.io/kubernetes-id: AbishekSMahesh-poi-map-app
    backstage.io/kubernetes-namespace: AbishekSMahesh
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-deploy/AbishekSMahesh-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/dev-pipelines/ns/AbishekSMahesh/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/k8s/ns/AbishekSMahesh/deployments/AbishekSMahesh-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.a1jxqhzp.eastus2.aroapp.io/#https://github.com/rhdh-deploy/AbishekSMahesh-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://AbishekSMahesh-poi-map-app-AbishekSMahesh.apps.a1jxqhzp.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/ryanj"
  system: workshop-system-AbishekSMahesh
  consumesApis:
    - gateway-api-AbishekSMahesh
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-AbishekSMahesh
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/ryanj"
